# Generated by Django 3.1.3 on 2020-12-31 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerremarks',
            old_name='comment',
            new_name='remarks_obtained',
        ),
        migrations.RemoveField(
            model_name='lecturerremarks',
            name='student_names',
        ),
        migrations.AddField(
            model_name='lecturerremarks',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_give_remarks', to='students.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturerremarks',
            name='project_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='students.project'),
        ),
        migrations.AddField(
            model_name='lecturerremarks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_obtained_remarks', to='students.student'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_project', to='students.student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentRemarks',
        ),
    ]
